#ifndef SCALAR_DEFINITIONS_H
#define SCALAR_DEFINITIONS_H

#include "scalar.h"
#include "scalar_abs.h"
#include "scalar_acos.h"
#include "scalar_add.h"
#include "scalar_asin.h"
#include "scalar_atan.h"
#include "scalar_constant.h"
#include "scalar_cos.h"
#include "scalar_eq.h"
#include "scalar_exp.h"
#include "scalar_expression.h"
#include "scalar_ge.h"
#include "scalar_globals.h"
#include "scalar_gt.h"
#include "scalar_if_then_else.h"
#include "scalar_le.h"
#include "scalar_log.h"
#include "scalar_lt.h"
#include "scalar_max.h"
#include "scalar_min.h"
#include "scalar_mul.h"
#include "scalar_named_expression.h"
#include "scalar_ne.h"
#include "scalar_negative.h"
#include "scalar_one.h"
#include "scalar_power.h"
#include "scalar_sign.h"
#include "scalar_sin.h"
#include "scalar_sqrt.h"
#include "scalar_std.h"
#include "scalar_tan.h"
#include "scalar_visitor_typedef.h"
#include "scalar_zero.h"

#endif // SCALAR_DEFINITIONS_H
